### ISSUE TITLE
Spreadsheet isn't generated reliably

### ISSUE THREAD

**Issue by shinji257** [BigBrainAFK/hbg-spreadsheet-builder#2]
When using -auto (even if the upload options are off) or if you have upload/uploadDrive set to y (regardless of -auto being present or not) it fails to generate a spreadsheet.

The only time it generates proper is if you run the script without -auto and either leaving both -upload and -uploadDrive out or setting them to n respectively.  It will pause at the end which makes it harder to automate.

There are a few different scenarios in here (based on testing).
* When having the script automatically the file doesn't seem to be committed to disk in time for the upload routines.
* When running with -auto it seems that process.exit() may be bailing out the whole process without allowing existing promise tasks to complete and flush data.  The delay from the prompt when -auto isn't present may have been enough otherwise.

**Comment by BigBrainAFK** [comment]
the write to disk is asynchronus and has an await combined with it so that this shouldnt even happen. imma investigate this
